name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: echo "build" # TODO_CHECKLIST - [ ] Replace with real build commands
      - name: Test
        run: echo "run tests" # TODO_CHECKLIST - [ ] Replace with real test command
      - name: Deploy
        if: success()
        run: bash cicd/deploy.sh
